language: python

python:
    - "2.6"
    - "2.7"

# Install FFmpeg.
before_install: sudo apt-get install -qq libavformat-dev libavcodec-dev libswscale-dev libavutil-dev

# Install build requirements.
install: pip install --use-mirrors cython

# Currently only building, not testing.
script: make build
