language: python

python:
    - "2.6"
    - "2.7"
env:
    - LIBRARY=ffmpeg
    - LIBRARY=libav

before_install:
    - scripts/test-setup
    - pip install --use-mirrors cython nose

install:
    - make build

script:
    - nosetests
