language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"

# Install FFmpeg.
before_script: sudo aptitude -y -q install libvlc-dev

# Install build requirements.
install: pip install --use-mirrors cython

# Currently only building, not testing.
script: make build
