language: python

sudo: false

addons:
    apt:
        packages:
            - libjpeg-dev
            - libfreetype6-dev
            - zlib1g-dev
            - yasm
            - ffmpeg # We will install our own, but we need the dependencies

cache:
    directories:
        - tests/assets # Cache files from the FATE suite.
        - venvs # Python virtualenvs and compiled FFmpeg/Libav.

python:
    #- "2.6" # Retire??
    - "2.7"
    #- "3.3" # Retire??
    - "3.4"

env:
    - LIBRARY=ffmpeg LIBRARY_VERSION=1.2.2
    #- LIBRARY=ffmpeg LIBRARY_VERSION=2.2.4
    - LIBRARY=ffmpeg LIBRARY_VERSION=2.7
    #- LIBRARY=libav  LIBRARY_VERSION=9.10
    - LIBRARY=libav  LIBRARY_VERSION=11.4

before_install:
    - scripts/build-deps

install:
    - scripts/build

script:
    - scripts/test
