language: python

python:
    - "2.6"
    - "2.7"
env:
    - LIBRARY=ffmpeg
    - LIBRARY=libav

before_install: ./.travis-setup
install: pip install --use-mirrors cython

# Currently only building, not testing.
script: make build
